In [181]:
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
import tensorflow as tf
from sklearn.preprocessing import StandardScaler, LabelEncoder
import matplotlib.pyplot as plt
from tensorflow import keras
from tensorflow.keras.utils import to_categorical
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

df = pd.read_csv("./breast_cancer.csv")

In [183]:
print(df)

     Unnamed: 0  mean radius  mean texture  mean perimeter  mean area  \
0             0        17.99         10.38          122.80     1001.0   
1             1        20.57         17.77          132.90     1326.0   
2             2        19.69         21.25          130.00     1203.0   
3             3        11.42         20.38           77.58      386.1   
4             4        20.29         14.34          135.10     1297.0   
..          ...          ...           ...             ...        ...   
564         564        21.56         22.39          142.00     1479.0   
565         565        20.13         28.25          131.20     1261.0   
566         566        16.60         28.08          108.30      858.1   
567         567        20.60         29.33          140.10     1265.0   
568         568         7.76         24.54           47.92      181.0   

     mean smoothness  mean compactness  mean concavity  mean concave points  \
0            0.11840           0.27760      

In [185]:
X = df.drop("label", axis=1)
y = df["label"] 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [187]:
# Split the dataset into training and test sets
# Standardize the data
scaler = StandardScaler()
X = scaler.fit_transform(X)

In [189]:
le = LabelEncoder()
y_encoded = le.fit_transform(y)     
y_onehot = to_categorical(y_encoded)

In [191]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((455, 31), (114, 31), (455,), (114,))

In [193]:
from sklearn.svm import SVC

clf_svm = SVC(random_state=0)
clf_svm.fit(X_train, y_train)

pred_svm = clf_svm.predict(X_test)

print("\n--- SVM Classifier ---")
print("SVM 정확도:", accuracy_score(y_test, pred_svm))


--- SVM Classifier ---
SVM 정확도: 0.9122807017543859


In [195]:
print("\n--- SVM Classifier ---")
print(confusion_matrix(y_test, pred_svm))


--- SVM Classifier ---
[[40  7]
 [ 3 64]]


In [220]:
# 모델 생성
svm = SVC(random_state=42)

# 학습
svm.fit(X_train, y_train)

# 예측
y_pred = svm.predict(X_test)

# 정확도
print("SVM 정확도:", accuracy_score(y_test, y_pred))

SVM 정확도: 0.9122807017543859


In [199]:
from sklearn.linear_model import LogisticRegression

model_lr = LogisticRegression(max_iter=1000, random_state=0)
model_lr.fit(X_train, y_train)
y_pred_lr = model_lr.predict(X_test)


print("\n--- Logistic Regression Classifier ---")
print("Logistic Regression 정확도:", accuracy_score(y_test, y_pred_lr))


--- Logistic Regression Classifier ---
Logistic Regression 정확도: 0.9736842105263158


In [201]:
print("\n--- Logistic Regression Classifier ---")
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_lr))


--- Logistic Regression Classifier ---
Confusion Matrix:
 [[46  1]
 [ 2 65]]


In [222]:
# 모델 생성
lr = LogisticRegression(max_iter=1000, random_state=42)

# 학습
lr.fit(X_train, y_train)

# 예측
y_pred = lr.predict(X_test)

# 정확도
print("Logistic Regression 정확도:", accuracy_score(y_test, y_pred))


Logistic Regression 정확도: 0.9736842105263158


In [205]:
from sklearn.tree import DecisionTreeClassifier

model_dt = DecisionTreeClassifier(random_state=0)
model_dt.fit(X_train, y_train)
y_pred_dt = model_dt.predict(X_test)

print("\n--- Decision Tree Classifier ---")
print("Decision Tree 정확도:", accuracy_score(y_test, y_pred_dt))


--- Decision Tree Classifier ---
Decision Tree 정확도: 0.8947368421052632


In [207]:
print("\n--- Decision Tree Classifier ---")
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_dt))


--- Decision Tree Classifier ---
Confusion Matrix:
 [[43  4]
 [ 8 59]]


In [224]:
# 모델 생성
dt = DecisionTreeClassifier(random_state=42)

# 학습
dt.fit(X_train, y_train)

# 예측
y_pred = dt.predict(X_test)

# 정확도
print("Decision Tree 정확도:", accuracy_score(y_test, y_pred))


Decision Tree 정확도: 0.9210526315789473


In [211]:
from sklearn.ensemble import RandomForestClassifier

model_rf = RandomForestClassifier(random_state=0)
model_rf.fit(X_train, y_train)
y_pred_rf = model_rf.predict(X_test)

print("\n--- Random Forest Classifier ---")
print("Random Forest Accuracy:", accuracy_score(y_test, y_pred_rf))


--- Random Forest Classifier ---
Random Forest Accuracy: 0.9824561403508771


In [213]:
print("\n--- Random Forest Classifier ---")
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_rf))


--- Random Forest Classifier ---
Confusion Matrix:
 [[46  1]
 [ 1 66]]


In [226]:
# 모델 생성
rf = RandomForestClassifier(random_state=42)

# 학습
rf.fit(X_train, y_train)

# 예측
y_pred = rf.predict(X_test)

# 정확도
print("Random Forest 정확도:", accuracy_score(y_test, y_pred))


Random Forest 정확도: 0.956140350877193
